import { CourseReleVant } from './courseRelevant.model';
import { CourseRating } from 'src/models/courseRating.model';
import { TestUser } from './testUser.model';
import { CourseRatingSummary } from './courseRatingSummary.model';
import { Classroom } from './classroom.model';
import { Account } from "./account.model"
import { Subject } from './subject.model';
import { Teacher } from './teacher.model';
import { CourseSchedule } from './courseSchedule.model';
import { UserRating } from './userRating.model';

export class Course {
  id: string =  "";
  name: string =  "";
  code: string =  "";
  courseAvatar: string =  "";
  courseThumbnail: string =  "";
  courseBanner: string =  "";
  shortSummary: string =  "";
  courseInfo1: string =  "";
  courseInfo2: string =  "";
  price: any =  0;
  priceDiscount: any =  0;
  studentNum: any =  0;
  status: any =  0;
  order: any =  0;
  rating: any =  0;
  isShowHome: any =  0;
  classRoomId: string =  "";
  classRoomName: string =  "";
  subjectId: string =  "";
  subjectName: string =  "";
  teacherId: any =  "";
  teacherName: any =  "";
  accountId: string =  "";
  accountName: string =  "";
  createdDate: string =  "";
  modifiedDate: string =  "";
  createdBy: string =  "";
  modifiedBy: string =  "";
  promotionTime: string =  "";
  totalRating: any =  0;
  totalStudent: any =  0;
  currentRate: any =  0;
  userRating: UserRating = new UserRating();
  averageRating: any =  0;
  teachers: Teacher[] = [];
  subject: Subject = new Subject();
  accounts: Account[] = [];
  courseSchedules: CourseSchedule[] = [];
  classRoom: Classroom = new Classroom();
  testUsers: TestUser[] = [];
  courseRatingSummary: CourseRatingSummary = new CourseRatingSummary();
  courseRatings: CourseRating[] = [];
  courseRelevants: CourseReleVant[] = []; 
  isPassCourse: boolean = false;
}
