export class Notification {
    id =  "";
    title =  "";
    content =  "";
    createdDate =  "";
    createdBy =  "";
    modifiedDate =  "";
    modifiedBy =  "";
    routerLink =  "";
    notificationTypeId =  "";
    isShowAdmin : any;
    isShowUser : any;
    roleId =  "";
    isManual : any;
    status : any;
    accounts =  "";
    isRead =  0;
    key =  "";
    userName =  "";
    name =  "";
    email =  "";
    address =  "";
    phone =  "";
    avatar =  "";
    identityNo =  "";
    fromUserName =  "";
    fromName =  "";
    fromEmail =  "";
    fromAddress =  "";
    fromPhone =  "";
    fromAvatar =  "";
    fromIdentityNo =  ""
}